SpentEnergy/SpentEnergy/Models/spent.cs
namespace SpentEnergy.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("spentenergy.spent")]
    public partial class Spent
    {
        public int ID { get; set; }

        public int ID_DEV { get; set; }

        public float? TENSION { get; set; }

        public float? POTENCY { get; set; }

        public float? CALC { get; set; }

        public float? VALUE_MED { get; set; }

        public DateTime? HOUR_REG { get; set; }

        public virtual Device device { get; set; }
    }
}

SpentEnergy/SpentEnergy/Controllers/DevicesController.cs
using SpentEnergy.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SpentEnergy.Controllers
{
    public class DevicesController : Controller
    {

        Context db = new Context();

        // GET: Devices
        public ActionResult Index()
        {
            return View();
        }


        public void saveDevice(String nrDev, String nameDev)
        {
            if (nrDev.Equals("") || nameDev.Equals(""))
            {
                throw new Exception("Informe os dados corretamente!!");
            }
            Device device = new Device() {
                NR_DEV = nrDev,
                NAME_DEV = nameDev
            }; 

            db.device.Add(device);

            db.SaveChanges();
        }
    }
}

SpentEnergy/SpentEnergy/Controllers/SpentsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SpentEnergy.Models;
using SpentEnergy.Models.ModelView;

namespace SpentEnergy.Controllers
{
    public class SpentsController : Controller
    {
        private Context db = new Context();

        public ActionResult Index()
        {
            var spent = db.spent.Include(s => s.device);
            return View(spent.ToList());
        }

        public ActionResult InfoSpents()
        {
            var info = new Infos();
            info.Potency = 0;
            info.Tension = 0;
            info.Calc = 0;
            info.ValueMed = 0;

            db.spent.ToList()
                .ForEach(x =>
                    info = new Infos()
                    {
                        Potency = info.Potency + Convert.ToDecimal(x.POTENCY),
                        Tension = info.Tension + Convert.ToDecimal(x.TENSION),
                        Calc = info.Calc + Convert.ToDecimal(x.CALC),
                        ValueMed = info.ValueMed + Convert.ToDecimal(x.VALUE_MED)
                    }
                );

            return Json(info, JsonRequestBehavior.AllowGet);
        }


        public ActionResult ChartConsumption(String type, int year, int month, int day)
        {
            var chartDevices = db.device.OrderBy(x => x.ID).Select(x =>
                new ChartDevice()
                {
                    IdDev = x.ID,
                    NameDisp = x.NAME_DEV
                }
            ).ToList();

            foreach (ChartDevice chartDevice in chartDevices)
            {
                chartDevice.ChartDev = new List<Chart>();
                if (type == "M")
                {
                    chartDevice.ChartDev = db.spent.ToList().
                        Where(x => x.ID_DEV == chartDevice.IdDev && Convert.ToDateTime(x.HOUR_REG).Year == year)
                        .GroupBy(x => Convert.ToDateTime(x.HOUR_REG).Month).
                        Select(x => new Chart
                        {
                            AxisX = x.Key,
                            AxisY = Decimal.Parse(x.Average(a => a.CALC).ToString())
                        }).ToList();
                }

                if (type == "D")
                {
                    chartDevice.ChartDev = db.spent.ToList().
                        Where(x => x.ID_DEV == chartDevice.IdDev && Convert.ToDateTime(x.HOUR_REG).Year == year
                       && Convert.ToDateTime(x.HOUR_REG).Month == month)
                        .GroupBy(x => Convert.ToDateTime(x.HOUR_REG).Day).
                        Select(x => new Chart
                        {
                            AxisX = x.Key,
                            AxisY = Decimal.Parse(x.Average(a => a.CALC).ToString())
                        }).ToList();
                }

                if (type == "H")
                {
                    chartDevice.ChartDev = db.spent.ToList().
                        Where(x => x.ID_DEV == chartDevice.IdDev && Convert.ToDateTime(x.HOUR_REG).Year == year
                       && Convert.ToDateTime(x.HOUR_REG).Month == month && Convert.ToDateTime(x.HOUR_REG).Day == day)
                        .GroupBy(x => Convert.ToDateTime(x.HOUR_REG).Hour).
                        Select(x => new Chart
                        {
                            AxisX = x.Key + 1,
                            AxisY = Decimal.Parse(x.Average(a => a.CALC).ToString())
                        }).ToList();
                }
            }
            return Json(chartDevices, JsonRequestBehavior.AllowGet);
        }


        public ActionResult ChartPotency(String type, int year, int month, int day)
        {
            var chartDevices = db.device.OrderBy(x => x.ID).Select(x =>
                new ChartDevice()
                {
                    IdDev = x.ID,
                    NameDisp = x.NAME_DEV
                }
            ).ToList();

            foreach (ChartDevice chartDevice in chartDevices)
            {
                chartDevice.ChartDev = new List<Chart>();
                if (type == "M")
                {
                    chartDevice.ChartDev = db.spent.ToList().
                        Where(x => x.ID_DEV == chartDevice.IdDev && Convert.ToDateTime(x.HOUR_REG).Year == year)
                        .GroupBy(x => Convert.ToDateTime(x.HOUR_REG).Month).
                        Select(x => new Chart
                        {
                            AxisX = x.Key,
                            AxisY = Decimal.Parse(x.Average(a => a.POTENCY).ToString())
                        }).ToList();
                }

                if (type == "D")
                {
                    chartDevice.ChartDev = db.spent.ToList().
                        Where(x => x.ID_DEV == chartDevice.IdDev && Convert.ToDateTime(x.HOUR_REG).Year == year
                       && Convert.ToDateTime(x.HOUR_REG).Month == month)
                        .GroupBy(x => Convert.ToDateTime(x.HOUR_REG).Day).
                        Select(x => new Chart
                        {
                            AxisX = x.Key,
                            AxisY = Decimal.Parse(x.Average(a => a.POTENCY).ToString())
                        }).ToList();
                }

                if (type == "H")
                {
                    chartDevice.ChartDev = db.spent.ToList().
                        Where(x => x.ID_DEV == chartDevice.IdDev && Convert.ToDateTime(x.HOUR_REG).Year == year
                       && Convert.ToDateTime(x.HOUR_REG).Month == month && Convert.ToDateTime(x.HOUR_REG).Day == day)
                        .GroupBy(x => Convert.ToDateTime(x.HOUR_REG).Hour).
                        Select(x => new Chart
                        {
                            AxisX = x.Key + 1,
                            AxisY = Decimal.Parse(x.Average(a => a.POTENCY).ToString())
                        }).ToList();
                }
            }

            return Json(chartDevices, JsonRequestBehavior.AllowGet);
        }

        public ActionResult ChartSpents(String type, int year, int month, int day)
        {
            var chartDevices = db.device.OrderBy(x => x.ID).Select(x =>
                new ChartDevice()
                {
                    IdDev = x.ID,
                    NameDisp = x.NAME_DEV
                }
            ).ToList();

            foreach (ChartDevice chartDevice in chartDevices)
            {
                chartDevice.ChartDev = new List<Chart>();
                if (type == "M")
                {
                    chartDevice.ChartDev = db.spent.ToList().
                        Where(x => x.ID_DEV == chartDevice.IdDev && Convert.ToDateTime(x.HOUR_REG).Year == year)
                        .GroupBy(x => Convert.ToDateTime(x.HOUR_REG).Month).
                        Select(x => new Chart
                        {
                            AxisX = x.Key,
                            AxisY = Decimal.Parse(x.Sum(a => a.VALUE_MED).ToString())
                        }).ToList();
                }

                if (type == "D")
                {
                    chartDevice.ChartDev = db.spent.ToList().
                        Where(x => x.ID_DEV == chartDevice.IdDev && Convert.ToDateTime(x.HOUR_REG).Year == year
                       && Convert.ToDateTime(x.HOUR_REG).Month == month)
                        .GroupBy(x => Convert.ToDateTime(x.HOUR_REG).Day).
                        Select(x => new Chart
                        {
                            AxisX = x.Key,
                            AxisY = Decimal.Parse(x.Sum(a => a.VALUE_MED).ToString())
                        }).ToList();
                }

                if (type == "H")
                {
                    chartDevice.ChartDev = db.spent.ToList().
                        Where(x => x.ID_DEV == chartDevice.IdDev && Convert.ToDateTime(x.HOUR_REG).Year == year
                       && Convert.ToDateTime(x.HOUR_REG).Month == month && Convert.ToDateTime(x.HOUR_REG).Day == day)
                        .GroupBy(x => Convert.ToDateTime(x.HOUR_REG).Hour).
                        Select(x => new Chart
                        {
                            AxisX = x.Key + 1,
                            AxisY = Decimal.Parse(x.Sum(a => a.VALUE_MED).ToString())
                        }).ToList();
                }
            }
            return Json(chartDevices, JsonRequestBehavior.AllowGet);
        }

        public ActionResult ChartPieInfo(String type, int year)
        {

            var spents = db.spent.ToList();

            var total = spents.Where(x => Convert.ToDateTime(x.HOUR_REG).Year == year)
                .OrderBy(x => Convert.ToDateTime(x.HOUR_REG).Month)
                .GroupBy(x => Convert.ToDateTime(x.HOUR_REG).Month).ToList()
                .Select(x =>
                new
                {
                    value = Convert.ToDecimal(x.Sum(s => (type == "P" ? s.POTENCY :
                    (type == "T" ? s.TENSION : (type == "C" ? s.CALC : s.VALUE_MED))))),
                    month = Convert.ToDateTime(x.First().HOUR_REG).Month
                }).ToList();
            var total_array = new Decimal[12];

            total.ForEach(x =>
                total_array[x.month - 1] = x.value
            );

            return Json(total_array, JsonRequestBehavior.AllowGet);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SpentEnergy/SpentEnergy/Views/Spents/_cadDevice.cshtml
<div class="modal fade" id="cadDeviceModal" tabindex="-1" role="dialog" aria-labelledby="cadDeviceLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="cadDeviceLabel">Modal title</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form id="formCadDevice">
                <div class="modal-body">
                    <div class="form-group col col-md-6">
                        <label for="formGroupExampleInput">Número Dispositivo</label>
                        <input type="text" class="form-control" id="nr_dev" placeholder="Número Dispositivo" required>
                    </div>
                    <div class="form-group col col-md-12">
                        <label for="formGroupExampleInput2">Nome Dispositivo</label>
                        <input type="text" class="form-control" id="name_dev" placeholder="Nome Dispositivo" required>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Fechar</button>
                    <button id="saveDevice" type="submit" class="btn btn-primary">Salvar</button>
                </div>
            </form>
        </div>
    </div>
</div>
<script>
    $('#formCadDevice').submit(function () {
        let nrDev = $('#nr_dev').val();
        let nameDev = $('#name_dev').val();
        debugger;
        $.ajax({
            url: '@Url.Action("saveDevice", "Devices")',
            method: 'POST',
            data: {
                nrDev: nrDev,
                nameDev: nameDev
            }
        }).done(function () {
            alert("Dispositivo cadastrado com sucesso!!");
        }).fail(function (erro) {
            alert("Erro de cadastro!!");
        });
    });
</script>

SpentEnergy/SpentEnergy/Views/Spents/_chartConsumption.cshtml
<div class="col-md-12" style="padding:0;">
    <div class="header-info">Consumo Médio Anual</div>
    <hr style="margin:0" />
    <div class="row header-control">
        <div class="col-md-3">
            <label for="select-devices-type">Tipo:</label>
            <select class="form-control" id="select-devices-type" onchange="alterValueDevices()">
                <option value="M">Mêses</option>
                <option value="D">Dias</option>
                <option value="H">Horas</option>
            </select>
        </div>
        <div id="day-devices" class="form-group" style="margin:0 10px; display:none">
            <label for="day-input-devices">Dia:</label>
            <input id="day-input-devices" class="form-control" type="number" min="1" max="31" placeholder="Dia" value="1" oninput="alterValueDevices()" />
        </div>
        <div id="month-devices" class="form-group" style="margin:0 10px; display: none;">
            <label for="month-input-devices">Mês:</label>
            <input id="month-input-devices" class="form-control" type="number" min="1" max="12" placeholder="Mês" value="1" oninput="alterValueDevices()" />
        </div>
        <div id="year-devices" style="margin:0 10px;">
            <label for="year-input-devices">Ano:</label>
            <input id="year-input-devices" class="form-control" type="number" min="2019" placeholder="Ano" value="2019" oninput="alterValueDevices()" />
        </div>
    </div>
    <hr style="margin:0" />
</div>
<div class="col-md-12">
    <div class="card-body data_chart">
        <canvas id="devices-chart" class="devices-chart-chart" height="168"></canvas>
    </div>
</div>

<script>

    $(document).ready(function () {
        let chart_atua_devices = [];
        let colors_chart_devices = [];
        let devices_chart_canvas = document.getElementById("devices-chart");
        let devices_chart = new Chart(devices_chart_canvas.getContext('2d'), {
            type: 'line',
            data: {
                fillOpacity: 0.3,
                labels: months,
                datasets: []
            },
            options: {
                scales: {
                    yAxes: [{
                        scaleLabel: {
                            display: true,
                            labelString: 'Consumo (kWh)'
                        }
                    }]
                },
                maintainAspectRatio: false
            }
        });


        let time_consumpition = setInterval(function () {
             let type = $('#select-devices-type').children("option:selected").val();
            $.ajax({
                url: '@Url.Action("ChartConsumption", "Spents")',
                method: 'GET',
                data: {
                    type: type,
                    year: $('#year-input-devices').val(),
                    month: $('#month-input-devices').val(),
                    day: $('#day-input-devices').val()

                }
            }).done(function (data) {
                let chart_devices = [];
                colors_chart_devices = random_colors(data.length, 100);
                for (let i = 0; i < data.length; i++) {
                    let value = [];
                    for (let x = 0; x < data[i]['ChartDev'].length; x++) {
                        value[data[i]['ChartDev'][x]['AxisX'] - 1] = data[i]['ChartDev'][x]['AxisY'];
                    }
                    chart_devices.push(
                        {
                            label: data[i]['NameDisp'],
                            data: value,
                            backgroundColor: 'transparent',
                            borderColor: colors_chart_devices[i],
                            id: data[i]['IdDev']
                        }
                    );
                }
                if ((alter_devices)
                    || ((chackAlter(chart_atua_devices, chart_devices) || devices_chart.data.datasets.length === 0) && atulization_global)) {
                    devices_chart.data.labels = alterType(type);
                    devices_chart.data.datasets = chart_devices;
                    chart_atua_devices = chart_devices;
                    devices_chart.update();
                    alter_devices = false;
                }

            }).fail(function (error) {
                alert('Erro no carregamento do Grafico de Consumo!!');
                console.log(error);
                clearInterval(time_consumpition);
            });
        }, 1000);
    });

    $('#select-devices-type').change(function () {
        switch ($(this).children('option:selected').val()) {
            case 'M':
                $('#year-devices').css('display', 'block');
                $('#month-devices').css('display', 'none');
                $('#day-devices').css('display', 'none');
                break;
            case 'D':
                $('#year-devices').css('display', 'block');
                $('#month-devices').css('display', 'block');
                $('#day-devices').css('display', 'none');
                break;
            case 'H':
                $('#year-devices').css('display', 'block');
                $('#month-devices').css('display', 'block');
                $('#day-devices').css('display', 'block');
                break;
        }

    });

    let alter_devices = false
    let alterValueDevices = function () {
        alter_devices = true;
    };
</script>

SpentEnergy/SpentEnergy/Views/Spents/_chartPieConsumption.cshtml
<div class="card-body">
    <div class="row">
        <div class="col-md-12">
            <div class="header-info">
                <span>Consumo Geral Mensal</span>
            </div>
            <hr style="margin:0"/>
            <div class="row header-control">
                <div class="col-md-6">
                    <label for="select-weekend-type">Tipo:</label>
                    <select class="form-control" id="select-weekend-type" onchange="alterValueWeekend()">
                        <option value="P">Potencia</option>
                        <option value="T">Tensão</option>
                        <option value="C">Consumo</option>
                        <option value="G">Gasto</option>
                    </select>
                </div>
                <div id="year-weekend" class="col-md-5" style="margin:0 10px;">
                    <label for="year-input-weekend">Ano:</label>
                    <input  id="year-input-weekend" class="form-control" type="number" min="2019" placeholder="Ano" value="2019" oninput="alterValueWeekend()" />
                </div>
            </div>
        </div>
    </div>
    <hr style="margin: 0;" />
    <div class="row">
        <div class="col-md-12" >
            <div class="data_chart">
                <canvas id="weekend_chart" height="177"></canvas>
            </div>
        </div>
    </div>
</div>
<script>
    $(document).ready(function () {


        let chart_atua_weekend = [];

        let weekend_chart_canvas = document.getElementById("weekend_chart");
        let weekend_chart = new Chart(weekend_chart_canvas.getContext('2d'), {
            type: 'pie',
            data: {
                labels: months,
                datasets: []
            },
            options: {
                maintainAspectRatio: false
            }
        });


        let time_cunsumption_pie = setInterval(function () {
            let type = $('#select-weekend-type').children("option:selected").val();
            $.ajax({
                url: '@Url.Action("ChartPieInfo","Spents")',
                method: 'GET',
                data: {
                    type: type,
                    year: $('#year-input-weekend').val()
                }
            }).done(function (data) {
                let atu = false;
                for (let i = 0; i < data.length; i++) {
                    data[i] = data[i] === 0 ? undefined : data[i];
                    if (chart_atua_weekend.length === 0 || chart_atua_weekend[i] !== data[i]) {
                        atu = true;
                    }
                }
                if ((atu && atulization_global) || alter_weekend) {
                    weekend_chart.data.datasets = [{
                        data: data,
                        backgroundColor: random_colors(data.length, 7),
                    }];
                    weekend_chart.update();
                    chart_atua_weekend = data;
                    alter_weekend = false
                }
            }).fail(function (error) {
                alert('Erro no carregamento do Grafico de Consumo Geral!!');
                console.log(error);
                clearInterval(time_cunsumption_pie);
            });
        }, 1000);
    });

    let alter_weekend = false
    let alterValueWeekend = function () {
        alter_weekend = true;
    };
</script>

SpentEnergy/SpentEnergy/Views/Spents/_chartPotency.cshtml
<div class="col-md-12" style="padding:0;">
    <div class="header-info">Potência Média Anual</div>
    <hr style="margin:0" />
    <div class="row header-control">
        <div class="col-md-3">
            <label for="select-potency-type">Tipo:</label>
            <select class="form-control" id="select-potency-type" onchange="alterValuePotency()">
                <option value="M">Mêses</option>
                <option value="D">Dias</option>
                <option value="H">Horas</option>
            </select>
        </div>
        <div id="day-potency" class="form-group" style="margin:0 10px; display:none">
            <label for="day-input-potency">Dia:</label>
            <input id="day-input-potency" class="form-control" type="number" min="1" max="31" placeholder="Dia" value="1" oninput="alterValuePotency()" />
        </div>
        <div id="month-potency" class="form-group" style="margin:0 10px; display: none;">
            <label for="month-input-potency">Mês:</label>
            <input id="month-input-potency" class="form-control" type="number" min="1" max="12" placeholder="Mês" value="1" oninput="alterValuePotency()" />
        </div>
        <div id="year-potency" style="margin:0 10px;">
            <label for="year-input-potency">Ano:</label>
            <input id="year-input-potency" class="form-control" type="number" min="2019" placeholder="Ano" value="2019" oninput="alterValuePotency()" />
        </div>
    </div>
    <hr style="margin:0" />
</div>
<div class="col-md-12 ">
    <div class="card-body data_chart">
        <canvas id="potency-chart" height="168"></canvas>
    </div>
</div>


<script>

    $(document).ready(function () {
        let chart_atua_potency = [];
        let colors_chart_potency = [];
        let potency_chart_canvas = document.getElementById("potency-chart");
        let potency_chart = new Chart(potency_chart_canvas.getContext('2d'), {
            type: 'line',
            data: {
                labels: months,
                datasets: []
            },
            options: {
                scales: {
                    yAxes: [
                        {
                            scaleLabel: {
                                labelString: "Potência (kW)",
                                display: true
                            }
                        }
                    ]
                },
                maintainAspectRatio: false
            }
        });


        let time_potency = setInterval(function () {
            let type = $('#select-potency-type').children("option:selected").val();
            $.ajax({
                url: '@Url.Action("ChartPotency", "Spents")',
                method: 'GET',
                data: {
                    type: type,
                    year: $('#year-input-potency').val(),
                    month: $('#month-input-potency').val(),
                    day: $('#day-input-potency').val()

                }
            }).done(function (data) {
                let chart_potency = [];
                colors_chart_potency = random_colors(data.length, 100);
                for (let i = 0; i < data.length; i++) {
                    let value = [];
                    for (let x = 0; x < data[i]['ChartDev'].length; x++) {
                        value[data[i]['ChartDev'][x]['AxisX'] - 1] = data[i]['ChartDev'][x]['AxisY'];
                    }
                    chart_potency.push(
                        {
                            label: data[i]['NameDisp'],
                            data: value,
                            backgroundColor: 'transparent',
                            borderColor: colors_chart_potency[i],
                            id: data[i]['IdDev']
                        }
                    );
                }
                if ((alter_potency)
                    || ((chackAlter(chart_atua_potency, chart_potency) || potency_chart.data.datasets.length === 0) && atulization_global)) {
                    potency_chart.data.labels = alterType(type);
                    potency_chart.data.datasets = chart_potency;
                    chart_atua_potency = chart_potency;
                    potency_chart.update();
                    alter_potency = false;
                }

            }).fail(function (error) {
                alert('Erro no carregamento do Grafico de Potencia!!');
                console.log(error);
                clearInterval(time_potency);
            });
        }, 1000);
    });

    $('#select-potency-type').change(function () {
        switch ($(this).children('option:selected').val()) {
            case 'M':
                $('#year-potency').css('display', 'block');
                $('#month-potency').css('display', 'none');
                $('#day-potency').css('display', 'none');
                break;
            case 'D':
                $('#year-potency').css('display', 'block');
                $('#month-potency').css('display', 'block');
                $('#day-potency').css('display', 'none');
                break;
            case 'H':
                $('#year-potency').css('display', 'block');
                $('#month-potency').css('display', 'block');
                $('#day-potency').css('display', 'block');
                break;
        }

    });

    let alter_potency = false
    let alterValuePotency = function () {
        alter_potency = true;
    };
</script>

SpentEnergy/SpentEnergy/Views/Spents/_infoSpents.cshtml
<div class="card-body">
    <div class="row">
        <div class="col-md-12 header-info">
            <span>Informações</span>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <ul class="list-group">
                <li class="list-group-item">
                    <div class="row">
                        <div class="col-md-2 col-sm-1">
                            <i class="fa fa-bolt"></i>
                        </div>
                        <div class="col-md-6 col-sm-7">Tensão</div>
                        <div class="col-md-4 col-sm-4">
                            <span id="tension" class="badge badge-primary badge-pill">00.00 (V)</span>
                        </div>
                    </div>
                </li>

                <li class="list-group-item">
                    <div class="row">
                        <div class="col-md-2 col-sm-1">
                            <i class="fa fa-car-battery"></i>
                        </div>
                        <div class="col-md-6 col-sm-7">Potência</div>
                        <div class="col-md-4 col-sm-4">
                            <span id="potency" class="badge badge-primary badge-pill">00.00 (kW)</span>
                        </div>
                    </div>
                </li>
                <li class="list-group-item">
                    <div class="row">
                        <div class="col-md-2 col-sm-1">
                            <i class="fa fa-solar-panel"></i>
                        </div>
                        <div class="col-md-6 col-sm-7">Consumo</div>
                        <div class="col-md-4 col-sm-4">
                            <span id="calc" class="badge badge-primary badge-pill">00.00 (kWh)</span>
                        </div>
                    </div>
                </li>
                <li class="list-group-item">
                    <div class="row">
                        <div class="col-md-2">
                            <i class="fa fa-hand-holding-usd"></i>
                        </div>
                        <div class="col-md-6">Valor Médio Gasto</div>
                        <div class="col-md-4">
                            <span id="value_med" class="badge badge-primary badge-pill">00.00 (R$)</span>
                        </div>
                    </div>
                </li>
            </ul>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="dropdown-divider"></div>
        </div>
        <div class="col-md-12">
            <div class="bottom-info  text-dark">
                <i class="fa fa-calendar-day mr-2"></i>
                @DateTime.Today.Date
            </div>
        </div>
    </div>
</div>

<script>

    let time_Info = setInterval(function () {
        $.ajax({
            url: '@Url.Action("InfoSpents", "Spents")',
            method: 'GET'
        }).done(function (data) {
            $('#tension').text(data['Tension'] + ' (V)');
            $('#potency').text(data['Potency'] + ' (kW)');
            $('#calc').text(data['Calc'] + ' (kWh)');
            $('#value_med').text(data['ValueMed'] + ' (R$)');
        }).fail(function (error) {
            alert('Erro no carregamento das informações!!');
            console.log(error);
            clearInterval(time_Info);
        })
    }, 1000);


</script>